(ns polix.bytecode.runtime
  "Runtime support for bytecode-compiled policies.

  Provides helper functions called from generated bytecode. These functions
  handle operations that are complex to inline directly in bytecode, such as
  conflict residual construction and document path access."
  (:import
   [clojure.lang Keyword RT PersistentArrayMap]))

(def ^:const conflict-kw
  "The :conflict keyword, interned once."
  :conflict)

(def ^:const satisfied-result
  "The satisfied result - empty map."
  PersistentArrayMap/EMPTY)

(defn get-path-value
  "Gets a value from a document at a path.

  Path is an array of keywords. Returns nil if any segment is missing."
  ^Object [^Object document ^objects path]
  (loop [idx 0
         current document]
    (if (or (nil? current) (>= idx (alength path)))
      current
      (recur (inc idx) (RT/get current (aget path idx))))))

(defn build-conflict
  "Builds a conflict residual from pre-computed template and witness.

  Template is an Object array: [path-vec, constraint-form].
  Returns {path-vec [[:conflict constraint-form witness]]}."
  ^Object [^objects template ^Object witness]
  (let [path-vec (aget template 0)
        constraint-form (aget template 1)]
    {path-vec [[conflict-kw constraint-form witness]]}))

(defn build-conflict-multi
  "Builds a conflict residual for multiple constraints.

  Template is an Object array: [path-vec, [constraint-form1, constraint-form2, ...]].
  Constraint-idx indicates which constraint failed.
  Returns {path-vec [[:conflict constraint-form witness]]}."
  ^Object [^objects template ^long constraint-idx ^Object witness]
  (let [path-vec (aget template 0)
        constraint-forms ^objects (aget template 1)
        constraint-form (aget constraint-forms constraint-idx)]
    {path-vec [[conflict-kw constraint-form witness]]}))

(defn intern-keyword
  "Interns a keyword from a string. Used for path access."
  ^Keyword [^String s]
  (Keyword/intern s))
